name: Deploy App 

on: 
  push:
    branches: 
      -master 

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: action/setup-node@v1
        with: 
          node-version: 14.15.1
      - run: npm run build
      - run: gh-pages -d build